# Generated by Django 5.1.3 on 2026-04-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0007_products_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='payment_method',
            field=models.CharField(default='Tunai', max_length=50),
        ),
    ]
