# Generated by Django 5.1.3 on 2026-04-27 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0009_alter_products_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='warranty',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
