# Generated by Django 5.1.3 on 2026-04-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_products_warranty_alter_products_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='warranty',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
