# Generated by Django 5.1.3 on 2026-04-27 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0011_alter_products_stock_alter_products_warranty'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='customer_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='customer_wa',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
