# Generated by Django 6.0.3 on 2026-05-14 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0014_categorytype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Merek & Kategori', 'verbose_name_plural': 'Daftar Merek'},
        ),
        migrations.AlterModelOptions(
            name='categorytype',
            options={'verbose_name': 'Tipe Merek', 'verbose_name_plural': 'Daftar Tipe Merek'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Katalog Produk', 'verbose_name_plural': 'Daftar Produk'},
        ),
        migrations.AlterModelOptions(
            name='sales',
            options={'verbose_name': 'Riwayat Penjualan', 'verbose_name_plural': 'Data Penjualan'},
        ),
        migrations.AlterModelOptions(
            name='salesitems',
            options={'verbose_name': 'Item Terjual', 'verbose_name_plural': 'Detail Item Terjual'},
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='tax',
            new_name='diskon',
        ),
        migrations.RenameField(
            model_name='sales',
            old_name='tax_amount',
            new_name='diskon_amount',
        ),
    ]
