# Generated by Django 6.0.3 on 2026-05-25 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0016_sales_cashier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='sales',
            name='code',
            field=models.CharField(max_length=10),
        ),
    ]
