# Generated by Django 6.0.3 on 2026-05-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0020_alter_products_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorytype',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
