# Generated by Django 6.0.3 on 2026-05-25 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0021_alter_categorytype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sales',
            name='customer_address',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='customer_wa',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
