# Generated by Django 6.0.6 on 2026-06-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0023_inventorylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='buy_price',
            field=models.FloatField(default=0),
        ),
    ]
