# Generated by Django 6.0.6 on 2026-06-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0024_products_buy_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='condition',
            field=models.CharField(choices=[('BARU', 'Baru'), ('BEKAS_A', 'Bekas Grade A'), ('BEKAS_B', 'Bekas Grade B'), ('RUSAK', 'Rusak/Minus')], default='BARU', max_length=20),
        ),
        migrations.AlterField(
            model_name='salesitems',
            name='qty',
            field=models.IntegerField(default=0),
        ),
    ]
