"""
Django settings for pos project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--w(dug*va_megpa25w$gmv8o6+f8!fg_*m1^u$)z25pab0hicm'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'unfold',
    'unfold.contrib.filters',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'posApp.apps.posAppConfig',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pos.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pos.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'posApp.validators.MaximumLengthValidator',
        'OPTIONS': {
            'max_length': 15,
        }
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'id'

# --- PERUBAHAN ZONA WAKTU KE WIB ---
TIME_ZONE = 'Asia/Jakarta'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    # location of your application, should not be public web accessible 
    './static',
)

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
LOGIN_REDIRECT_URL = '/'
LOGIN_URL = '/login'


# --- TAMBAHAN UNTUK FITUR UNGGAH GAMBAR PRODUK ---
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# -------------------------------------------------

# =============================================================
# KONFIGURASI UNFOLD ADMIN (MODERN MINIMALIST THEME)
# =============================================================
from django.urls import reverse_lazy

UNFOLD = {
    "SITE_TITLE": "El-Tech Admin",
    "SITE_HEADER": "El-Tech Administrasi",
    "SITE_SUBHEADER": "Panel Administrasi Sistem",
    "SITE_DROPDOWN": [
        {
            "icon": "laptop_mac",
            "title": "Buka Website POS",
            "link": "/",
        },
    ],
    "SITE_URL": "/",
    # Menampilkan Logo El-Tech
    "SITE_ICON": lambda request: "/static/posApp/assets/default/logo-toko.png",
    "SITE_FAVICONS": [
        {
            "rel": "icon",
            "href": lambda request: "/static/posApp/assets/default/logo-toko.png",
            "type": "image/png",
        },
    ],
    "SITE_SYMBOL": None,
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "SHOW_BACK_BUTTON": True,
    "ENVIRONMENT": "posApp.admin.environment_callback",
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Navigasi Utama",
                "separator": False,
                "collapsible": False,
                "items": [
                    {
                        "title": "Dashboard",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": "Manajemen Toko",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Daftar Produk",
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:posApp_products_changelist"),
                    },
                    {
                        "title": "Merek & Kategori",
                        "icon": "label",
                        "link": reverse_lazy("admin:posApp_category_changelist"),
                    },
                    {
                        "title": "Tipe Merek",
                        "icon": "layers",
                        "link": reverse_lazy("admin:posApp_categorytype_changelist"),
                    },
                    {
                        "title": "Log Inventory",
                        "icon": "archive",
                        "link": reverse_lazy("admin:posApp_inventorylog_changelist"),
                    },
                ],
            },
            {
                "title": "Data Transaksi",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Data Penjualan",
                        "icon": "receipt_long",
                        "link": reverse_lazy("admin:posApp_sales_changelist"),
                    },
                    {
                        "title": "Detail Item Terjual",
                        "icon": "list_alt",
                        "link": reverse_lazy("admin:posApp_salesitems_changelist"),
                    },
                ],
            },
            {
                "title": "Manajemen Pengguna",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "Pengguna",
                        "icon": "manage_accounts",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                    },
                    {
                        "title": "Grup Akses",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                    },
                ],
            },
        ],
    },
    # Menghapus kustomisasi COLORS agar menggunakan default django-unfold yang terjamin sempurna
}